name: Bug report
description: Report a bug with Admin Page Framework
labels: ["Bug"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report! For a security issue, please report it to: admin-page-framework@michaeluno.jp
    - type: textarea
      attributes:
          label: Description
          description: Please write a brief description of the bug, including the actual and expected behaviors.
          placeholder: |
              There seems to be a problem that is "...". I expect that "...".
      validations:
          required: true

    - type: textarea
      attributes:
          label: Steps to reproduce
          description: Please provide the steps to reproduce the bug.
          placeholder: |
              1. Go to '...'
              2. Fill out '...'
              3. Submit '...'
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots, screen recording clips, or code snippets
          description: |
              A screenshot or screen recording clip which demonstrates the bug will help understand the problem for others. To create a GIF screen recording, you can use LIEcap: https://www.cockos.com/licecap/
              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
              Sharing a code snippet that demonstrates the issue also helps. For short snippets, post them here, or use Gist for long ones or mulitple files: https://gist.github.com
              Please ensure that your code can be run by others to reproduce and debug the issue.
      validations:
          required: false

    - type: textarea
      attributes:
          label: Environment
          description: |
              Please list the versions of the related software that you are using.
          placeholder: |
            - Admin Page Framework version
            - WordPress version
            - Browser(s) (e.g. "Microsoft Edge 96", "Google Chrome 99", etc.)
            - OS (e.g. "Windows 10", "Ubuntu 18" etc.)
      validations:
          required: false

    - type: dropdown
      id: existing
      attributes:
          label: Please confirm that you have searched existing issues in this repository.
          description: https://github.com/michaeluno/admin-page-framework/issues
          multiple: true
          options:
             - 'Yes'
             - 'No'
      validations:
          required: true

    - type: dropdown
      id: plugins
      attributes:
          label: Please confirm that the problem occurs with the default theme and all the plugins deactivated except "Admin Page Framework - Loader".
          multiple: true
          options:
             - 'Yes'
             - 'No'
      validations:
          required: true