<?php 
$_aClassFiles = array( 
	"AdminPageFrameworkLoader_AdminPage"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/AdminPageFrameworkLoader_AdminPage.php", 
	"AdminPageFrameworkLoader_AdminPage_About"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/about/AdminPageFrameworkLoader_AdminPage_About.php", 
	"AdminPageFrameworkLoader_AdminPage_About_ChangeLog"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/about/AdminPageFrameworkLoader_AdminPage_About_ChangeLog.php", 
	"AdminPageFrameworkLoader_AdminPage_About_Credit"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/about/AdminPageFrameworkLoader_AdminPage_About_Credit.php", 
	"AdminPageFrameworkLoader_AdminPage_About_Guide"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/about/AdminPageFrameworkLoader_AdminPage_About_Guide.php", 
	"AdminPageFrameworkLoader_AdminPage_About_Welcome"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/about/AdminPageFrameworkLoader_AdminPage_About_Welcome.php", 
	"AdminPageFrameworkLoader_AdminPage_Help"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/help/AdminPageFrameworkLoader_AdminPage_Help.php", 
	"AdminPageFrameworkLoader_AdminPage_Help_FAQ"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/help/AdminPageFrameworkLoader_AdminPage_Help_FAQ.php", 
	"AdminPageFrameworkLoader_AdminPage_Help_Informationt"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/help/AdminPageFrameworkLoader_AdminPage_Help_Informationt.php", 
	"AdminPageFrameworkLoader_AdminPage_Help_Report"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/help/AdminPageFrameworkLoader_AdminPage_Help_Report.php", 
	"AdminPageFrameworkLoader_AdminPage_Help_Tip"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/help/AdminPageFrameworkLoader_AdminPage_Help_Tip.php", 
	"AdminPageFrameworkLoader_AdminPage_Tool"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/tool/AdminPageFrameworkLoader_AdminPage_Tool.php", 
	"AdminPageFrameworkLoader_AdminPage_Tool_Minifier"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/tool/AdminPageFrameworkLoader_AdminPage_Tool_Minifier.php", 
	"AdminPageFrameworkLoader_Bootstrap"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/boot/AdminPageFrameworkLoader_Bootstrap.php", 
	"AdminPageFrameworkLoader_Demo"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/demo/AdminPageFrameworkLoader_Demo.php", 
	"AdminPageFrameworkLoader_AdminPage_Help_Information"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/help/AdminPageFrameworkLoader_AdminPage_Help_Informationt.php", 
	"names',"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/tool/AdminPageFrameworkLoader_AdminPage_Tool_Minifier.php", 
	"named"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/tool/AdminPageFrameworkLoader_AdminPage_Tool_Minifier.php", 
);
