<?php 
$_aClassFiles = array( 
	"AdminPageFrameworkLoader_AdminPage"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/AdminPageFrameworkLoader_AdminPage.php", 
	"AdminPageFrameworkLoader_AdminPage_Help"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/help/AdminPageFrameworkLoader_AdminPage_Help.php", 
	"AdminPageFrameworkLoader_AdminPage_Help_About"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/help/AdminPageFrameworkLoader_AdminPage_Help_About.php", 
	"AdminPageFrameworkLoader_AdminPage_Help_Debug"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/help/AdminPageFrameworkLoader_AdminPage_Help_Debug.php", 
	"AdminPageFrameworkLoader_AdminPage_Help_Example"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/help/AdminPageFrameworkLoader_AdminPage_Help_Example.php", 
	"AdminPageFrameworkLoader_AdminPage_Help_FAQ"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/help/AdminPageFrameworkLoader_AdminPage_Help_FAQ.php", 
	"AdminPageFrameworkLoader_AdminPage_Help_Guide"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/help/AdminPageFrameworkLoader_AdminPage_Help_Guide.php", 
	"AdminPageFrameworkLoader_AdminPage_Help_Informationt"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/help/AdminPageFrameworkLoader_AdminPage_Help_Informationt.php", 
	"AdminPageFrameworkLoader_AdminPage_Help_Report"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/help/AdminPageFrameworkLoader_AdminPage_Help_Report.php", 
	"AdminPageFrameworkLoader_AdminPage_Help_Tip"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/help/AdminPageFrameworkLoader_AdminPage_Help_Tip.php", 
	"AdminPageFrameworkLoader_AdminPage_Tool"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/tool/AdminPageFrameworkLoader_AdminPage_Tool.php", 
	"AdminPageFrameworkLoader_AdminPage_Tool_Minifier"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/tool/AdminPageFrameworkLoader_AdminPage_Tool_Minifier.php", 
	"AdminPageFrameworkLoader_AdminPageWelcome"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/dashboard/AdminPageFrameworkLoader_AdminPageWelcome.php", 
	"AdminPageFrameworkLoader_AdminPageWelcome_ChangeLog"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/dashboard/welcome/AdminPageFrameworkLoader_AdminPageWelcome_ChangeLog.php", 
	"AdminPageFrameworkLoader_AdminPageWelcome_Credit"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/dashboard/welcome/AdminPageFrameworkLoader_AdminPageWelcome_Credit.php", 
	"AdminPageFrameworkLoader_AdminPageWelcome_Guide"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/dashboard/welcome/AdminPageFrameworkLoader_AdminPageWelcome_Guide.php", 
	"AdminPageFrameworkLoader_AdminPageWelcome_Welcome"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/dashboard/welcome/AdminPageFrameworkLoader_AdminPageWelcome_Welcome.php", 
	"AdminPageFrameworkLoader_Demo"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/demo/AdminPageFrameworkLoader_Demo.php", 
	"AdminPageFrameworkLoader_Bootstrap"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/boot/AdminPageFrameworkLoader_Bootstrap.php", 
	"AdminPageFrameworkLoader_Option"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/boot/AdminPageFrameworkLoader_Option.php", 
	"AdminPageFrameworkLoader_AdminPage_Help_Information"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/help/AdminPageFrameworkLoader_AdminPage_Help_Informationt.php", 
	"names',"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/tool/AdminPageFrameworkLoader_AdminPage_Tool_Minifier.php", 
	"named"	=>	AdminPageFrameworkLoader_Registry::$sDirPath . "/include/class/admin/admin-page-framework/tool/AdminPageFrameworkLoader_AdminPage_Tool_Minifier.php", 
);
